### ISSUE TITLE
Region filter not working?

### ISSUE THREAD

**Issue by rogeriosmorais** [0xbs/premade-groups-filter#130]
I tried:

- oce
- region == oce
- region == "oce"

And nothing works. I don't get any results in the list.

**Comment by 0xbs** [comment]
Do you have the [Premade Regions](https://github.com/0xbs/premade-regions) addon installed?
First and third expression should both work, second expression is invalid (comparing string with boolean).

**Comment by 0xbs** [comment]
Separate addon because this is a Oceanic/US-only problem and not relevant for EU or Asia.

Using just `not oce` should be fine, braces are not needed here (but also not wrong).

Not sure why you still see groups. One issue might be that you have multiple addons (PGF, LFM+) for filtering the list. They might interfere with each other. Please try with just PGF installed.

Another issue might be new (just created) groups: Filtering is done via the group leader's name which is not available immediately for new groups but takes some seconds. `oce` is a hard filter in the sense that if the name/region is not yet available, the group is removed. `not oce` is a weak filter as new groups are not considered oceanic but neutral groups until the leader's name becomes available. However as you already see OCE next to the dungeon's name, leader name and region info should already be available.

**Comment by 0xbs** [comment]
As other players mentioned the same problem, I assume it is simply that the filter does not work for new groups. I created a FAQ entry: https://github.com/0xbs/premade-groups-filter/wiki/FAQ#my-region-filter-not-oce-still-shows-some-oce-groups
