### ISSUE TITLE
Filtering of realms

### ISSUE THREAD

**Issue by Petoovee** [0xbs/premade-groups-filter#14]
Due to increasing popularity of r.io, this addon could gain significant traction by allowing filtering of given realms, in interest of joining groups where the leaders realm is not at maximum capacity.

**Comment by 0xbs** [comment]
Yes this would be indeed be an interesting filter for a lot of people. But not a trivial one. Since the leader board capacity cannot be retrieved in-game by an addon, this would have to be done on a server that regularly retrieves the leader boards and pushes new updates to the addon, just like the raider.io addon. The effort of implementing such a service and maintaining it is way too much for me, even raider.io collects money via Patreon and advertisements to finance their service. So the only solution I see is that the raider.io addon (which pulls this data and is updated regularly anyway) provides that data in-game to other addons such as PGF. Afaik, this is currently not the case, otherwise they would most likely show that in their tooltips. So I think this request is currently best filed to the raider.io developers.

Another thing I'd like to say: While I am also a user of the raider.io addon, I really dislike how it destroys the community. Players are essentially reduced to two numbers: ilvl and rio. And both say little to nothing about how good someone plays, not even if they really know the dungeon mechanics. But it looks like we have to live with that, since Blizzard even wants to show M+ progression on character pages in the future instead of reducing leader boards to the top 10 groups.

**Comment by Petoovee** [comment]
I had plans on how to accomplish the server issue myself should pgf support realm filtering, however if the solution appeals to you we might work together on this.
Basically, while a raspberry pi 3b+ is "weak" I have succesfully managed to use it to fetch 50k warcraft logs profiles on it daily for over a week. Due to server loads I was requested to stop that. But my point is that the pi should be able to accomplish such a task.

Then the procedure would be very similar to what my now discontinued addon did; update the database, push it to github then pull it from github to the desired computer and folder using a bat file. I have failed to see any limitations to bandwidth on github, but seeing how much bigger corporations use it for larger and more frequent files I doubt that would be an issue.

Although users might be reluctant to use .bat files, that end would require more thought. If this is of interest to you, then I would gladly use my now idle raspberry for this purpose for the foreseeable future.

**Comment by Petoovee** [comment]
Whoops...

**Comment by 0xbs** [comment]
Added you in-game
