### ISSUE TITLE
Make window moveable or respect other windows

### ISSUE THREAD

**Issue by tryallthethings** [0xbs/premade-groups-filter#15]
Hi guys,

Thanks for the great addon!
I've got an improvement request. It would be great if the addon window would either be moveable or adjust its position to other, already existing windows. 
In my specific case the PGF addon is on top of the Raider.io addon and neither can be moved: 
![image](https://user-images.githubusercontent.com/11146296/52143429-b873ff80-265b-11e9-84c2-66e068f5fd7f.png)

Another small addition to this: The PGF window seems to be 1 pixel larger on the top and the bottom - both in my ElvUI and the default Blizzard interface.

Thanks,
Stefan

**Comment by 0xbs** [comment]
Interesting, since my raider.io window is on top of PGF. They might have changed something though. For a quick solution, just close the PGF window via its close button in the right top. Filtering is still active and the window will reopen when you reopen the dungeon finder.

I also wonder why the PGF window is larger for you. I am using the default Blizzard UI and it fits perfectly. Do you have a specific scaling factor set up? Does it look different for other scaling factors?

Will keep this open as moving would be a nice improvement.

**Comment by roots84** [comment]
I found another workaround in the meantime. You can "un-dock" the raider.io window and move it freely. I'm not using any kind of scaling and even in the default Blizzard UI it's a bit larger:
![image](https://user-images.githubusercontent.com/11146296/52309335-18daa800-29a0-11e9-9601-6df1dbd790d5.png)
![image](https://user-images.githubusercontent.com/11146296/52309385-432c6580-29a0-11e9-82ac-98a0bce77d4a.png)
![image](https://user-images.githubusercontent.com/11146296/52309454-7a9b1200-29a0-11e9-8d71-2e031240f2f9.png)

**Comment by 0xbs** [comment]
Will look into the size issue as soon as I am resubscribing to WoW (currently not much spare time).

**Comment by 0xbs** [comment]
With version `1.35-beta2` the window can now be unlocked and moved around freely.
