### ISSUE TITLE
Add Mythic+ Level as filter condition

### ISSUE THREAD

**Issue by Kamusksn** [0xbs/premade-groups-filter#155]
It's possible to add Mythic+ level to show only groups for that specific level and not +- 1 like the default blizzard interface does?

**Comment by 0xbs** [comment]
Not possible. Since the Battle for Azeroth Prepatch, the group name and comment are protected by Blizzard and can not be evaluated by any addon. See #136.

If you want a single key level only, do the trick mentioned in the [FAQ](https://github.com/0xbs/premade-groups-filter/wiki/FAQ#how-can-i-filter-by-mythic-key-level) and search by e.g. `15 16 17` to get `16` only.
