### ISSUE TITLE
Questions About Usage

### ISSUE THREAD

**Issue by ChrisKader** [0xbs/premade-groups-filter#164]
Hey @0xbs,

I have recently decided to start rewriting my addon (LFM+) which has similar functionality to Premade Groups Filter. After reviewing our addons [License](https://github.com/0xbs/premade-groups-filter/blob/master/LICENSE) my understanding is that I would need to ask for your permission to potentially use some of your code (based on [Section 10](https://github.com/0xbs/premade-groups-filter/blob/master/LICENSE#L256)). I do not wish to just take your code and make minor changes, but rather base some of my functionality and programming methodology to mirror yours, such as your methods of breaking out functions of the addon into "Modules".

I plan on updating my credits section to also include information about your contributions along with a link to your GitHub profile and of course the Premade Groups Filter GitHub project page along with your CurseForge and Wago.io addon pages.  am more than willing to share my code with you once done for your approval before releasing the updates to my addon.

My Discord ID is ![image](https://user-images.githubusercontent.com/633360/230154995-04e14b25-8f8c-47fc-a982-dc9ab5ac93ae.png)

**Comment by 0xbs** [comment]
Hey Chris,

great job on your addon, I always admired your much simpler user interface! 

Since your addon is under the same license as my addon (GPL v2), you may copy my code without asking for explicit permission as we share the same license. You must disclose the source code, however this is the case for WoW addon written in Lua anyway. I do not attach too much importance to a copyright notice, but I would appreciate it if you do put a small note in a file if you copy larger parts of code. A link on the project page is fine as well, but no requirement. Changes are visible though Git history anyway, no need to document them explicitly.

I sent you a friend request on Discord, however I rarely use Discord.

–B
