### ISSUE TITLE
Horrible user experience

### ISSUE THREAD

**Issue by AtrejuCodes** [0xbs/premade-groups-filter#167]
If you have to use syntax then at least do better examples. I don't know how this has 5m downloads. Horrible user experience.

**Comment by 0xbs** [comment]
Well, thank you for the feedback.

I put a lot of thoughts into user experience, but came to the conclusion that there is no way I can provide a UI that supports the same amount of options. So I went with the current split UI that supports some basic filters with input fields and the rest via expressions. I know that it is very hard for some players to get the expressions right, but you also learn a little bit about programming and learning new things is good. My hope was that the wiki pages would ease the pain a bit. Another limitation is the Blizzard API itself: Group search is quite protected since WorldQuestGroupFinder killed the servers. Also it's always a major pita to build a UI in WoW XML and Lua.

What is your favorite expression that you would like to see on the example page?

What concept should be better explained?

Do you have any feasible suggestions how a better UI could look like? Feel free to send me a hand drawn sketch or some Paint drawing.
