### ISSUE TITLE
Donations or other contributions?

### ISSUE THREAD

**Issue by toomuchpete** [0xbs/premade-groups-filter#187]
The most recent updates to PGF have added things that I've been wishing for for a _long_ time and I'd love to support development of this really critical addon. Do you have a place to receive donations or some other way to support what you're doing with this plugin?

**Comment by 0xbs** [comment]
Thank you for your kind words, they mean a lot to me. There is no donation set up at the moment. As far as I remember, you are the first one asking.

I thought about it for some days now and as I’m in the fortunate position to not depend on money from this addon, I suggest you donate it in my place to an organization or person around you that is in need of support.

If you have a lot to give, a key for game time would be the best gift for me. However that’s quite expensive since they changed it to two months only. 

Keep up your spirit and continue to give feedback!
