### ISSUE TITLE
Not Declined Button missing since 4.1 Update

### ISSUE THREAD

**Issue by Sunaruqtx** [0xbs/premade-groups-filter#191]
Hey,
with the 4.0 Update you introduced the "Not Declined" Button, it got removed with the Later updates, i would request bringing it back.
Thanks in Advance <3

**Comment by 0xbs** [comment]
Hi, I'm not completely sure if it will come back because I might need the space for a sorting dropdown.

Until then, you can always simply type `not declined` into the expression box to get the same filter.

If you also want to remove groups where your application timed out, use `not declined and not softdeclined`.

**Comment by 0xbs** [comment]
Button is back (for now) :)
