### ISSUE TITLE
Hide 'Advanced Filter Expression' window?

### ISSUE THREAD

**Issue by ppzz123** [0xbs/premade-groups-filter#192]
Hi,

Thanks for this addon, very handy.

Sorry if this has been asked before but is it possible to hide the Advanced Filter Expression window? I can click the cross to close it but that also closes the window on the right side of mentioned window (the window with all your timed/untimed runs) and I want to keep that one open.
![image](https://github.com/0xbs/premade-groups-filter/assets/29522211/fa764cd7-1282-4f74-9134-a3808f24c5dc)

Thanks in advance

**Comment by 0xbs** [comment]
The tooltip window on the right comes from Raider.io, I think they added some code to move it to the right when PGF is open. If you close or move the PGF window, the rio tooltip should reappear if you hover over an entry in the list.

If not, try the following:
- If you are not setting any filters anyway, you can disable PGF by unchecking the checkbox above the group list. – By the way, did you go into expert mode on purpose? Because if you click the maximize button, it will show you easier filters!
- You can make the PGF window movable in the options and move it somewhere else. Should be movable by default.
- Ditch the tooltip and install this formidable WeakAura, which shows you all your best runs and more below the LFG window: https://wago.io/QXJ4dN6pp

**Comment by ppzz123** [comment]
Thank you for your reply.

- Yes but amongst other things, I find the class colors and most importantly, the remember function for declines and/or timeouts super handy so that's why I didn't want to uncheck. However, I have tested it now with it set to unchecked and it seems those functions are still working so I think I'm just silly and always had it running unchecked. I must have recently, accidentally enabled the checkmark.
Yes I have seen the easier filters but I wanted to make the window as small as possible. Either way, with the checkmark set to unchecked my problem is solved.
- Noted thanks.
- Might consider it, thank you for the tip.
