### ISSUE TITLE
Key level filter per dungeon

### ISSUE THREAD

**Issue by LazarQt** [0xbs/premade-groups-filter#197]
I've been tinkering around with addons and sometimes hit technical limits so this is part feature request part question regarding some implementation details before I do unnecessary work.

Would it be possible to have a key level for each dungeon? I'm looking for specific keystone levels to push my dungeons bit by bit and am currently sifting through the list on the left hand side a lot. 

And since the default filter isn't perfect even when typing a specific range (e.g. 23-23 but 22 showing up for some reason or custom note) would it be possible to run it through some regex first?

Thanks and cheers.

**Comment by 0xbs** [comment]
The problem is that the group name and comment is protected by Blizzard since BfA, like the Battle.net ID. If you read the text with an addon, you get only a K-string like `|Kr1234|k`. It is basically a pointer to the actual string and works like a formatting directive. The UI renderer itself replaces it with the actual text.

The measure was done as a reaction to World Quest Group Finder because of it's massive impact on the group finder and also because it made world quests trivial.

This addon once had text search on group names and comments implemented, but I had to remove it eventually. As far as I know, there is no other source for the key level.

The search bar is the only way to set a key level filter. The search box itself is also protected in the sense that addons cannot change the text. You may not even paste to it as a player. Also all underlying search functions are protected.

**Comment by LazarQt** [comment]
Thank you for the detailed information. No surprise this hasn't been done yet then since it seems so obvious. 

Cheers
