### ISSUE TITLE
mprating filter stopped working

### ISSUE THREAD

**Issue by Lehren** [0xbs/premade-groups-filter#199]
![image](https://github.com/0xbs/premade-groups-filter/assets/8881212/8adc844b-f6ef-429a-8e50-816a50c29de3)

The filter for mythic+ key level does not work anymore. 
Also, the overview shows differing numbers for the mythic level than what seems to be advertised. The top +14 group shows as +13 etc. So either everyone is misadvertising it or the addon does not read something correctly.

**Comment by 0xbs** [comment]
The "M+ Rating" filter should filter by _rating_, not by key level. According to your screenshot, you should only see groups where the leader has a rating of at most 13.

Your screenshot still shows groups with a rating higher than 13, however all those groups are green colored, meaning they're new groups. For those new groups, the information about the leader and her rating is delayed and filtering has already been done when the rating arrives. This is usually fixed with a second click on search.

Filtering by key _level_ is not possible for addons due to restrictions from Blizzard. You may however type something like `14-16` or `15-15` into the standard search box.

Please also have a look at the FAQ in the Wiki tab. Almost everything should already been in there.
