### ISSUE TITLE
Add option to show spec instead of role icons

### ISSUE THREAD

**Issue by 0xbs** [0xbs/premade-groups-filter#201]
Suggestion: add an option to show spec icons instead of role icons in the dungeon list.

**Comment by moisalucian** [comment]
https://www.curseforge.com/wow/addons/premade-group-finder

Already done in this addon if helps to get inspiration

**Comment by moisalucian** [comment]
Would be an amazing enchancement

**Comment by moisalucian** [comment]
Hei, any news about this topic? 
This and Single Click sign ( both of them with toggle on off, for who don't like that) are the only reason keeping me from using this addon in front of others.

Thanks a lot!

**Comment by 0xbs** [comment]
Thanks for bringing this up, I will try to implement that next. I don't have much spare time at the moment unfortunately.

Signing up to a group with a single click is already a feature, have a look at the options.

**Comment by moisalucian** [comment]
Hei again, ty a lot for answer. That's amazing, coming back with this reply just so you know you're appreciated for your work!

**Comment by moisalucian** [comment]
Hmm, Not sure If I should do a new topic or not, I did think of additional enchancement and probably would be a hard thing to do:

Have an checkbox option to mark who's the leader of the party (specially for M+). If the mark is checked, to appear a small "crown" icon on top of the guy who's  the current party lead.

![image](https://github.com/user-attachments/assets/a86c3d4f-92bb-4ae1-a143-ca1a10ebaf0d)
![Party Lead](https://github.com/user-attachments/assets/e5a9dd43-ef5d-41a7-817c-12920e10ea31)

**Comment by 0xbs** [comment]
Version 5.9.0-beta now supports spec icons. You have to switch them on in the options (Esc → Options → Addons → PGF).

The leader crown was previously a feature of PGF, but I disabled it because Blizzard changed the sort order of group members, so the crown was misplaced as I am using a different order internally. Also, the crown is still visible in the group tooltip and I found the information not being important enough: It allows you to see which class/spec has the displayed group rating. But what should that tell me? A group with a good tank might still have bad dps/healers and vice versa. Been there often enough. I would consider bringing it back if you can give me a good enough reason @moisalucian

**Comment by moisalucian** [comment]
Uh nice, thanks a lot for spec icons. Since it's on beta version, i have to manually install that version to use it or CurseForge will automatically detect a new version? 

About the crown, I find it easy to see how's the lead of 10 groups in glance instead of hovering over each one to see the tooltip. And while indeed some people pass around the lead for better rating, in my experience higher rating player don't accept for no reason that responsability. They either know you or even if not, by passing the lead the them you have the chance to do the dung in time cause you get better people. And you know what they say, if you are the worst, there's no other way than going up an learning since others are good :) 

But that's debatable,  I was actually thinking this would be an easy option to be checked/unchecked by players in options, depending on preferences. That way, each one can customize however their hearth feels like and probably work for you is little to none, since you already did that ^_^ 

And now that you bringed that up, would also be nice for players to be able to sort the groups how they want, based on leader rating, based on their current key rating  or any other way you can think of.
I remember that on the other addon that I used as reference on all this suggestions (Premade Group Finder) I could select to sort it based on party lead rating for M+

At the moment seems something bugged, so I can't show also that option that I could select (I think they have to update it soon), but the result still works as intended:

![image](https://github.com/user-attachments/assets/8dffb3ba-77b0-4e1c-8b65-e4ce7cbba925)

**Comment by 0xbs** [comment]
> Since it's on beta version, i have to manually install that version to use it or CurseForge will automatically detect a new version?

Easiest way is to right click on an addon in CurseForge client application and select release type beta.

> About the crown, I find it easy to see how's the lead of 10 groups in glance instead of hovering over each one to see the tooltip.

Okay, but what information do you draw from the crown? Why does it make a difference for you if the warrior tank or if the fire mage has the crown? Why would you select a group or not?

> And now that you bringed that up, would also be nice for players to be able to sort the groups how they want, based on leader rating, based on their current key rating or any other way you can think of.

Groups are already sorted by leader rating. However, rating is loaded with a slight delay, so sorting might have already been completed when some of the slower leader ratings come in. Because the list is not resorted again, this might lead to some minor inconsistencies.

Custom sorting is already possible in "advanced mode", meaning if you click the minimize button on the PGF window. This brings up an input field where you can put a custom sort expression. See wiki on how to use that.

**Comment by moisalucian** [comment]
![image](https://github.com/user-attachments/assets/2c10e524-f03b-4c80-857f-0a0925e53803)

Another person with same opinion ^_^ Barely having few people on my new channel, but feels like one of them seems to have same opinion

**Comment by moisalucian** [comment]
Also I would add that if you look the picture in the right side, on the "unoccupied" slots in party for each one, you still see what roles are required. 


For example first party has a FDK inside, and still needs a tank, heal and 2 dps roles and I can see that from the unocuppied slots.
2nd party has a resto druid and 2 retries. Unocuppied slots are 1 tank 1 dps. 

That's also additional enchancement that is reallly nice :D

**Comment by 0xbs** [comment]
5.9.1-beta now supports:

* Larger square spec icons
* Option to show leader crown
* Option to show class bars (can be useful together witrh spec icons)
* Option to show missing roles

I still have some weird glitches where the class bar do not lign up with the class circles.

**Comment by moisalucian** [comment]
Jeez, all this changes are looking dope. 
I think you actually nailed this time, love it. 

I did test all of them and this kind of freedom for user to select how queue should look is great in my opinion and they are actually now visible and quite appealing to use.

Slight improvement I think would be the missing roles icons to be colored, I think it would be a plus and would be easier to differentiate them in a fraction of second when looking, but only if that wouldn't be too much hasle, when fixing that glitches you said.  Picture for reference
![image](https://github.com/user-attachments/assets/988c33ba-ab4e-4a2b-8cbf-837ab763e1b0)

But again, I think everything looks really great right now. Thanks a lot for openess to improvements!
