### ISSUE TITLE
Add option to filter for Augmentation Evoker

### ISSUE THREAD

**Issue by KaareGravesen** [0xbs/premade-groups-filter#203]
**Suggestion**
Add an option to filter for groups that already have an augmentation evoker.
We can use `dps_evokers == 0`, but that means that we'll never be paired with a Devastation Evoker.

**Comment by 0xbs** [comment]
Good suggestion, but hard to implement, because the spec is only availabe as a localized string. This means I would have to map for example "Verstärkung" to "Augmentation" for every language there is in the game. To make it a bit more complicated, German "Verstärkung" can also mean "Enhancement" in case of a Shaman.

So I'm afraid you will have to keep looking at the tooltip to get the exact spec for now.

**Comment by 0xbs** [comment]
Now possible in version 5.3.0 by using e.g. `augs == 0`
