### ISSUE TITLE
Augmentation Filter

### ISSUE THREAD

**Issue by Leomelati** [0xbs/premade-groups-filter#222]
As an Augmentation Evoker, it would be nice if we had a filter to hide groups that already have one.

**Comment by 0xbs** [comment]
Good suggestion, but hard to implement, because the spec is only availabe as a localized string. This means I would have to map for example "Verstärkung" to "Augmentation" for every language there is in the game. To make it a bit more complicated, German "Verstärkung" can also mean "Enhancement" in case of a Shaman.

So I'm afraid you will have to keep looking at the tooltip to get the exact spec for now.

**Comment by teelolws** [comment]
Could you not just use `GetSpecializationInfoByID(1473)`? Both that, and the premade finder, should show "Augmentation" in the player's local language.

**Comment by 0xbs** [comment]
Version 5.3.0-beta now supports specializations. Use `augs == 0` to remove all groups with augmentation evokers. See Keywords page for more details.

**Comment by teelolws** [comment]
I suggest an alternative like spec["Augumentation"] where in another locale the player can write spec["whatever"] in their local language. Like what you did with the boss filter.

**Comment by Leomelati** [comment]
@0xbs Thank you for the implementation!

**Comment by 0xbs** [comment]
Would be easy to do, but there are collisions without the class, for example:

- English "Restoration" for resto druids and resto shamans
- German "Verstärkung" for enhancement shamans and augmentation evokers

This would make the filter kind of useless.

**Comment by teelolws** [comment]
Truuue... maybe spec[evokers, "Augumentation"]?

**Comment by teelolws** [comment]
No I understand, just trying to help keep it friendlier for non-english speakers

**Comment by 0xbs** [comment]
Okay, I will have a look if I can do something like you suggested with both a localized class and spec name.

**Comment by 0xbs** [comment]
Possible since some time using `augs == 0`
