### ISSUE TITLE
Key Turns Red, Even When Applying As An Available Role

### ISSUE THREAD

**Issue by QuirkyTurtle904** [0xbs/premade-groups-filter#231]
"Why do groups I applied to have a red background?
The background is red (instead of green) if the group has no slot left for your role. Currently only works for Mythic+ groups. This might happen if the group leader invited other players with the same role in the meantime but did not decline your application. Consider aborting your application in this case and gain back one of your five possible pending applications. Applications cannot be cancelled automatically, because the corresponding function is protected by Blizzard."

After reviewing FAQ, the answer could not be found. When applying to a key as a Pally (who's higher io is in Holy) is applying as Ret, to a key with only a healer in the group. Since the dps position is open, the key should not turn red after applying. Yet it does. Why would this occur? Shouldn't it still be green?

**Comment by 0xbs** [comment]
Thanks for the report and also for reading the FAQ first. 

The feature uses the same logic as the "partyfit" option, which already has a complicated logic.

There are three sources for your spec in theory:

1. The spec your are currently in (only retail version)
2. The assigned role (only when in a group)
3. The selected roles when applying to a group (might be outdated or not available at all)

Currently I use 1. when single and 2. when in a group. For groups, 2. is the only option since I cannot read the spec of team members.

Using 3. when single and if the information is available could be an option with a fallback to 1.

#226 is a similar issue.

**Comment by 0xbs** [comment]
Closing this issue as I removed my custom red background altogether because Blizzard now provides its own red background if the group no longer matches your filters.
