### ISSUE TITLE
[Request] Add player realms info

### ISSUE THREAD

**Issue by Rustyb0y** [0xbs/premade-groups-filter#25]
I have already added this to my PGF to create a custom version (see files/images below)

The reason for this is that I play in Australia and joining groups or inviting players from US East/Mex/Brazil means I either suffer from high latency (300+) or they do.  Which is not ideal for doing high m+ keys.  I have also attached the notes I use to update PGF (PremadegroupsFilter.txt).  I don't mind doing this for every version and sharing it with my friends however it's very easy to implement.  I haven't added Europe obviously but that could also be easily done.

[PremadeGroupsFilter.txt](https://github.com/0xbs/premade-groups-filter/files/3507431/PremadeGroupsFilter.txt)

![pgf1](https://user-images.githubusercontent.com/54157890/63131937-d48d2c00-c002-11e9-88e4-79f9ff8c728f.png)
![pgf2](https://user-images.githubusercontent.com/54157890/63131939-d8b94980-c002-11e9-8821-b718623e9d94.png)
![pgf3](https://user-images.githubusercontent.com/54157890/63131970-ea025600-c002-11e9-9b89-2004f3b6812a.png)
![pgf4](https://user-images.githubusercontent.com/54157890/63132323-0f439400-c004-11e9-91f0-17c11e128db7.png)

**Comment by 0xbs** [comment]
Thank you for your contribution!

Let us split the suggestions into four features and talk about them separately:

1. Provides keywords to filter by region
2. Adds region dropdown to the PGF window
3. Adds colored region markers to the group list
4. Adds colored region markers to the applicants list

**Feature 1: Provides keywords to filter by region**

Perfect, will add this, but the list has to be completed with all other regions.

**Feature 2: Adds region dropdown to the PGF window**

Currently the PGF window is about the same size as the LFG window, which looks nice. Does your addition change the size of the window? We would have to make the upper part of the PGF window scrollable. Also, while I love Australia (was visiting east coast, center and the south west for six weeks in April and is was amazing!) this feature is only relevant for a part of the word. Europe won't care about it at all, which makes me wonder if we need a prominent filter in the UI.

**Feature 3: Adds colored region markers to the group list**

It is really nice to have the region information available right next to the groups, but you would have to make this optional (provide a checkbox in the settings window to switch this behavior on/off). People are already complaining about the green/red colors and also about the role listing in the tooltip. At least Europe will complain, because the region information is irrelevant over here. This is also a lot of work since settings do not exist at the moment (see issue #4).

**Feature 4: Adds colored region markers to the applicants list**

Same as in feature 3. Additionally, this is not really a feature of Premade Groups **Finder**, but rather of putting groups together, which makes me wonder if it should really be a part of PGF.

Soooo, what do you thing about the following:

We're dropping 2 and will implement 1, 3 and 4 in a separate addon, which provides the region information to PGF, which adds a keyword as suggested in feature 1. I already did this with the Raider.IO ratings and we could do it the same way here. All Oceanic players could happily install this additional addon, while the rest of the world will just ignore it. We would not even have to implement the European and Asian regions for this addon, which saves time. I am happy to help you with creating the addon or I can create a first draft and you add the features afterwards, just as you like. Let me know what you think.

**Comment by Rustyb0y** [comment]
Thanks for your response

Sounds good.

1,3,4. A separate module which people can download if needed sounds good.  If you could put together the framework/first draft with the basic parts implemented I should be able to flesh it out add extra realm info for filtering etc.

2. I agree, I don't even use this myself.  I made the expression window smaller to make up for the extra space up top.

**Comment by 0xbs** [comment]
Alright, I created a new addon: https://github.com/0xbs/premade-regions
You should have gotten an invitation with git push access. I did not yet test the addon on a live server.

The addon is not yet on CurseForge, but the plan is to release it there. I can set up that later.

Install git for Windows if you you’re on Windows, open a cmd in your addon folder and set your name and email and check out the addon using

    git clone https://github.com/0xbs/premade-regions.git PremadeRegions
    git config --global user.name "Rustyb0y"
    git config --global user.email "putEmailAdressHere"

You can then try out the addon and make modifications and commit them using

    git add .
    git commit -m "Describe your changes here"
    git push

I did not yet change the PGF addon to use the region information from this addon, this would be the next step.

**Comment by Rustyb0y** [comment]
Sure

**Comment by Rustyb0y** [comment]
Ok, I've set all that up and tested the addon.  I corrected a typo and so far all is working as it should.

**Comment by Rustyb0y** [comment]
Hi, just want to check to see if your still around?   All good if your busy.

**Comment by 0xbs** [comment]
I totally missed your last comment somehow, sorry about that! Unfortunately I’m on a short vacation until Friday, but will add the change in PGF afterwards and set up the CurseForge project.

**Comment by Rustyb0y** [comment]
All good, thanks for the reply

**Comment by 0xbs** [comment]
I created the addon on CurseForge: https://www.curseforge.com/wow/addons/premade-regions

New versions of the addon are automatically pushed if you tag a commit with a version number like 1.1 (don't forget to set the same version number in the TOC file):

    git commit -m "Updates version number in toc file to 1.1"
    git tag 1.1
    git push origin 1.1

If you tell me your CurseForge/Twitch name, I will add you as an addon maintainer.

Premade Groups Filter now supports the keywords `oce`, `usp`, `usm`, `usc`, `use`, `mex`, `bzl` and `region`.

**Comment by Rustyb0y** [comment]
My curseforge/twitch name is rustyb0y.

Should I be able to see the addon at the moment?

**Comment by 0xbs** [comment]
Addon was still under review until an hour ago, but has now been approved by CurseForge. I added you as an author, feel free to improve the description/etc. Let’s do further communication via email: b.saumweber@gmail.com
