### ISSUE TITLE
fullid, partialid, noid not functioning on retail mop remix

### ISSUE THREAD

**Issue by cdmichaelb** [0xbs/premade-groups-filter#261]
Please check FAQ and existing issue first:
- FAQ / Wiki: https://github.com/0xbs/premade-groups-filter/wiki/FAQ
- All Issues: https://github.com/0xbs/premade-groups-filter/issues?q=

### Game Version
Retail (but remix... still the same client)

### Lua error from Bugsack
```
None
```

### Screenshots
![image](https://github.com/0xbs/premade-groups-filter/assets/1451709/911404ab-7117-48cc-8baa-774272de75d3)

### Current behaviour
noid is not functioning (still shows instances that I have an id for) (partialid and fullid also seem to not be working)
(edited to remove the portion I found in faq that blizz protected)

### Steps to reproduce
1. Open premade dungeon list
2. Setup filters ...
3. Click on ...

### Expected behaviour
It shouldn't be finding raids I'm saved to (throne of thunder in this case).

**Comment by 0xbs** [comment]
I don't have an id yet on MoP Remix, so I can't really test it. Not sure why it won't work, but id matching has always been a bit fuzzy as dungeon names do not always match up between the id and the activity. Could you paste a screenshot of the id window as well?

(I tested `activityname:find("mogu") ~= nil` and it only shows Mogu'shan Vaults. Using `not activityname:find("foo") ~= nil` will find any group, because no group contains "foo".)

**Comment by n0proxy** [comment]
I've also been experiencing this - when using noid, I'm still shown groups that have bosses already-defeated when I myself have no bosses killed in that raid. And this is when using the blizzard filter to show only one raid.

**Comment by Knaledge** [comment]
I confirm that `noid` is non-functional in MoP Remix. Please consider addressing this!

**Comment by 0xbs** [comment]
I implemented the missing logic to detect the difficulty of old 10 and 25 player raids, issue should be fixed.
