### ISSUE TITLE
Search for multiple keywords

### ISSUE THREAD

**Issue by zmoose** [0xbs/premade-groups-filter#30]
Is there a method to search for multiple keywords?  ie: I want to search for 'ha-li' and 'houndlord' groups while in the vale to farm the mounts.  I looked through the documentation and tried using the activityname keyword but it didn't work.

activityname:find("ha-li")

**Comment by 0xbs** [comment]
The activity name is the one below the actual title of the group and in this case not very useful because it is always something like custom group. You also cannot search the actual group name, because starting with the Battle for Azeroth Prepatch, the group name is protected by Blizzard and can no longer be evaluated by any addon. It might be possible to search by `questid` if those are quest mobs. Other than that, you are out of luck and have to switch between the two searches manually.
