### ISSUE TITLE
Checkmarks Always Save Max Checked

### ISSUE THREAD

**Issue by Jdaddy0007** [0xbs/premade-groups-filter#51]
I love this addon and have used since Legion.  Thank you so much.  An issue I've had for a while now is that the check marks for group remember the max checked.  In other words, if I check Members (with added numbers), even if unchecked, will reappear checked with those same numbers next log in.  The only fix is to delete my PFG file in WTF Folder. Another example, I was with a Tank friend of mine last night, so I added a tank filter of 0 to 0, and I am a healer so it was set to 0 to 0.  So for the last week I have to uncheck Tank, even though I unchecked it the previous times.  Thanks for your help!

**Comment by Jdaddy0007** [comment]
Found a temporary solution: if you remove the numbers, then search, then reload game the settings are remembered.

**Comment by Rustyb0y** [comment]
I don't use the filter options and only use the advanced expression query.

I mainly use this `mythicplus and partyfit` and add some other options as required.  Then I use the blizzard filter to search for the key level I'm after.  If you just put in 15 in the blizzard filter it will show any groups that match your expression query and with the numbers 14,15 and 16 in them.

partyfit will always check your current party roles and only show groups advertising with the members you need

**Comment by 0xbs** [comment]
> Found a temporary solution: if you remove the numbers, then search, then reload game the settings are remembered.

That was the idea behind it. If you remove the numbers, it will get unchecked automatically; if you add a number, the checkbox gets checked. Looking back, this was probably a bad design decision. Maybe should have gone without any checkboxes for the number fields, but found it confusing as all other fields have checkboxes.

I also usually just use the filter `partyfit` in the advanced checkbox and nothing else. In the search bar, I type something like spires 15 (which actually works and sets up a server side filter for Spires of Ascension 14-16) since I am usually looking for specific dungeons.
