### ISSUE TITLE
Expressions to search for Names not working per examples in wiki/Keywords

### ISSUE THREAD

**Issue by mechiah** [0xbs/premade-groups-filter#57]
The first three examples under Names, do not work, copy-pasted I get an error message indicating "Symantic error in the filter expression".

eg, `leader:find("arthas")` gets the error message

If I instead use `leader==arthas` this will work, but requires correct, full spelling of the name including realm.

**Comment by 0xbs** [comment]
You are right, the example was incomplete, a full working example is `leader:find("arthas") ~= nil` because the [string.find function in Lua](https://www.lua.org/manual/5.1/manual.html#pdf-string.find) returns `nil` when the pattern was not found and the indices in the original string where this occurrence starts and ends if it was found. Documentation is also updated.
