### ISSUE TITLE
9.1.5 groups show in duplicate when signed up

### ISSUE THREAD

**Issue by wrightling** [0xbs/premade-groups-filter#65]
![duplicates](https://user-images.githubusercontent.com/1406395/144308127-8357e5a2-f59d-454d-9bd2-968c2176c329.png)

Every group I sign up for then shows in duplicate - in the screenshot I am signed up for 4 groups... all show twice.

The only error I see in bugack is:

> 21x [ADDON_ACTION_BLOCKED] AddOn 'PremadeGroupsFilter' tried to call the protected function 'GetPlaystyleString()'.
> [string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
> [string "=[C]"]: in function `GetPlaystyleString'
> [string "@FrameXML\LFGList.lua"]:3508: in function <FrameXML\LFGList.lua:3499>
> [string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
> [string "@FrameXML\LFGList.lua"]:2576: in function <FrameXML\LFGList.lua:2573>
> [string "=[C]"]: ?

**Comment by 0xbs** [comment]
I see the same behavior when applying for a group. However, groups also show up in duplicate when I disable all addons. So this issue is not related to PGF.

Regarding the error message in BugSack: this a known problem. Blizzard protected the function GetPlaystyleString(), most likely by mistake. There is nothing I can do about the error at the moment.
