### ISSUE TITLE
Filter m+ dungeons by "keys that improve score"

### ISSUE THREAD

**Issue by nocawy** [0xbs/premade-groups-filter#75]
A feature request:

Would it be possible to add a filter for m+ dungeons, which displays only the keys that can improve our score (i.e. keys higher than our highest timed run for given dungeon)?

**Comment by 0xbs** [comment]
It would probably be possible by using `C_PlayerInfo.GetPlayerMythicPlusRatingSummary("player")` and `C_MythicPlus.GetSeasonBestAffixScoreInfoForMap(mapId)` but looks rather complicated. Since you have to complete a key on both Tyrannical and Fortified, it can get a bit tricky to find out if you can improve your score this week in a specific dungeon. Wowhead has a [guide on the rating system](https://www.wowhead.com/guides/blizzard-mythic-plus-rating-score-in-game). I will keep this issue in mind and would appreciate a PR.

**Comment by kavenstan** [comment]
Is this possible without reading the protected name string to find the key level?

**Comment by 0xbs** [comment]
You are right, reading the key level is not possible, making this feature pretty much impossible. I should have thought more about the requirements.
