### ISSUE TITLE
group creation no longer possible.

### ISSUE THREAD

**Issue by aquila357** [0xbs/premade-groups-filter#76]
can't use auto-text during group creation any longer... this means it's impossible for me to use your add-on as long as I want to open a group (pvp) any longer. 

Please fix it - Thanks!

**Comment by 0xbs** [comment]
The problem is that I can't fix both #64 and this issue. Most people seem to be happier to see the play style in the tooltip and do not need the auto text.

Feel free to delete the content of `FixGetPlaystyleString.lua` (but keep the file) which will fix your issue but you will have to live with tainting errors.

Ultimately only Blizzard can fix this by unprotecting `GetPlaystyleString`
